name: base
author: development <development@metismachine.com>
description: Base template for the Skafos platform.
tags: python, machine learning,
repo: https://github.com/metismachine/base.template
version: 0.0.1
